baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'kb works'

[menu]
[[menu.main]]
  identifier = 'aanbod'
  name = 'aanbod'
  url = '/aanbod/'
  weight = 0
[[menu.main]]
  identifier = 'kennis'
  name = 'kennis'
  url = '/kennis/'
  weight = 1
[[menu.main]]
  identifier = 'over ones'
  name = 'over ones'
  url = '/over-kbworks/'
  weight = 2
[[menu.main]]
  identifier = 'contact'
  name = 'contact'
  url = '/contact/'
  weight = 3
