baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'kb works'

[menu]
[[menu.nav]]
  identifier = 'aanbod'
  name = 'aanbod'
  title = 'aanbod'
  url = '/aanbod/'
  pageref = '/aanbod/'
  weight = 0

[[menu.nav]]
  identifier = 'kennis'
  name = 'kennis'
  title = 'kennis'
  url = '/kennis/'
  pageref = '/kennis/'
  weight = 1

[[menu.nav]]
  identifier = 'over ones'
  name = 'over ones'
  title = 'over ones'
  url = '/over-kbworks/'
  pageref = '/over-kbworks/'
  weight = 2

[[menu.nav]]
  identifier = 'contact'
  name = 'contact'
  title = 'contact'
  pageref = '/contact/'
  url = '/contact/'
  weight = 3
